### ISSUE TITLE
Can ESLint Enforce String Literals But Allow Array Concat

### ISSUE THREAD

**Issue by rzec-r7** [rapid7/javascript-style-guide#14]
In reference to [6.4](https://github.com/rapid7/javascript-style-guide#6.4), we want to enforce string literals over string concat however we also want to allow array concat of string if cases where a variables might be undefined. We need to make sure the eslint rule for enforcing string literals does not conflict with that.

**Comment by tquetano-r7** [comment]
Confirmed, the `prefer-template` rule only applies to string concatenation, it does not apply to joining of arrays.
