### ISSUE TITLE
New Rule: Allow 1 Level Deep Nested Destructuring

### ISSUE THREAD

**Issue by rzec-r7** [rapid7/javascript-style-guide#15]
We need to add a new section that mentions allowing 1 level deep destructuring:

```js
{
  onClick = ({event: {target}}) {
    this.updateValue(target.value);
  }
}
```

**Comment by tquetano-r7** [comment]
This looks like it will need to be enfored by code review, as the current rules do not allow this level of specificity. A good discussion can be found [on the thread dedicated to this enhancement](https://github.com/eslint/eslint/issues/7973).
