### ISSUE TITLE
Rename section 9 to Classes with some extra context.

### ISSUE THREAD

**Issue by rzec-r7** [rapid7/javascript-style-guide#22]
[9](https://github.com/rapid7/javascript-style-guide#9) should be renamed to Classes.

We should also add a block of text at the top of the section that mentions that outside of React, the use of classes are generally discouraged as most things can be accomplished with a more functional approach however if you find you must use a class, these are some general guidelines for working with them.

**Comment by tquetano-r7** [comment]
Closed with #36
