### ISSUE TITLE
Add notes about strict rules only allowing 25 statements instead of 50 for 7.12

### ISSUE THREAD

**Issue by rzec-r7** [rapid7/javascript-style-guide#26]
We need to update [7.12](https://github.com/rapid7/javascript-style-guide#7.12) to include that fact that the strict rules will only allow 25 statements instead of 50 that the standard rules have.

**Comment by dcastellanos-r7** [comment]
Long methods are a thing, https://www.urbandictionary.com/define.php?term=Marathon%20Method

**Comment by tquetano-r7** [comment]
Closed with #34
