### ISSUE TITLE
Investigate ESLint's ability to automatically format objects when there are 2 or more elements in it

### ISSUE THREAD

**Issue by rzec-r7** [rapid7/javascript-style-guide#58]
With reference to [18.12](https://github.com/rapid7/javascript-style-guide#18.12), we want to look into the ability to have eslint automatically put object properties each on there own line when you have 2 or more which would be easier to read than how prettier formats it with a line length of 120.

**Comment by tquetano-r7** [comment]
This is now handled automatically by the `object-property-newline` rule.
