### ISSUE TITLE
Investigate if ESLint cant prevent 22.4 for after but allow before

### ISSUE THREAD

**Issue by rzec-r7** [rapid7/javascript-style-guide#64]
We want to investigate if ESLint can enforce the rule [22.4](https://github.com/rapid7/javascript-style-guide#22.4) in a way that allows underscores to be leading but not trailing.

**Comment by tquetano-r7** [comment]
The native ESLint does not provide this, but I can create a rapid7-specific ESLint rule that modifies the `no-dangling-underscore` rule in ESLint to only check if trailing and allow leading.

**Comment by tquetano-r7** [comment]
This has been solved by the new custom rule `rapid7/no-trailing-underscore`
